# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: Your awesome title
#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
date_format: "%A, %B %e, %Y" # Thursday, January 24, 2019
permalink: /:year-:month-:day/:title/
#paginate: 20
#paginate_path: "/blog/page:num/"

landing_page_links:
  - div_id: site-links
    links:
      - title: About me
        url: /about/
        fa_icon: question
      - title: My blog
        url: /blog/
        fa_icon: pencil
  - div_id: social-media-links
    links:
#      - title: Twitter
#        url: https://twitter.com/
#        fa_icon: twitter
      - title: Email
        url: /email/
        fa_icon: envelope
      - title: Reddit
        url: https://www.reddit.com/u/derekmaciel
        fa_icon: reddit-alien
      - title: GitHub
        url: https://github.com/dere
        fa_icon: github
      - title: LinkedIn
        url: https://www.linkedin.com/in/derekmaciel
        fa_icon: linkedin

sass:
  style: compressed
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
